events {
    worker_connections 1024;
}

http {
    upstream balanceador {
        server blue:80 weight=6;
        server green:80 weight=3;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://balanceador/;
        }

        location /blue/ {
            proxy_pass http://blue:80/;
        }

        location /green/ {
            proxy_pass http://green:80/;
        }
    }
}